# Default initial positions for left_arm_ur5e's ros2_control fake system

initial_positions:
  left_elbow_joint: 0
  left_shoulder_lift_joint: 0
  left_shoulder_pan_joint: 0
  left_wrist_1_joint: 0
  left_wrist_2_joint: 0
  left_wrist_3_joint: 0