# This config file is used ONLY by MuJoCo
controller_manager:
  ros__parameters:

    update_rate: 100  # Hz

    #plugin_telecamera
    mujoco_plugins:
      realsense_plugin:
        type: "mujoco_ros2_control_plugins/CameraPlugin"
        camera_publish_rate: 30.0
        width: 640
        height: 480
        camera_name: "realsense_d435"
        frame_id: "ignore_tf"

    #controllers
    scaled_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true