# src/shot_planning/config/logging_essential_params.yaml
#this file should be used only when in the logging_essential_mode
task_node:
  ros__parameters:

    #DEBUG PARAMETERS
    print_EEF_distance_and_position: true  # stampa della distanza e della posizione relativa tra tip dell'asta e pallina bianca alla fine dei movimenti


    #LOGGING PARAMETERS

    #ruckig shot generated trajectory  logging
    log_ruckig_trajectory: true                                                      # attiva log in file della traiettoria calcolata da Ruckig (in moveCartesianPathAsymmTriangle, tiro)
    csv_ruckig_trajectory_path: "data/csv/ruckig_logging/ruckig_trajectory_log.csv"  # percorso del file csv di log della traiettoria calcolata da Ruckig

    #type logging for only essential
    joints_logging_enabled: true
    cartesian_logging_enabled: true
    controller_logging_enabled: true

    #phase logging for only essential
    phase_1_logging_enabled: false    #fase1 -> andare in posa pre-approach
    phase_2_logging_enabled: false    #fase2 -> approach alla pallina
    phase_3_logging_enabled: false    #fase3 -> allontanamento all'indietro per prendere velocità
    phase_4_logging_enabled: true     #fase4 -> tiro
    phase_5_logging_enabled: false    #fase5 -> alzata per liberare il campo
    phase_6_logging_enabled: false    #fase6 -> scostamento dal tavolo per liberare il campo e la vista alla telecamera per prossima identifiazione
    

 