# src/shot_planning/config/shot_params.yaml
task_node:
  ros__parameters:

    approach_distance_from_ball_surface: 0.02             # distanza di avvicinamento alla pallina in metri (2 cm)
    shooting_distance_from_ball_surface: 0.04             # distanza di tiro dalla pallina in metri (4 cm)
    distance_deceleration_phase_fraction_radius: 2.00     # distanza di decelerazione espressa in frazione del raggio della pallina (1.00 = 1 raggio, 1.5 = 1.5 raggi ecc..) -> Consigliato da 1.5 a 2.0
    offset_correction_center_z: 0.000                     # correzione dell'offset del centro della pallina, per far colpire più in alto rispetto al centro della pallina (in metri)
    elevation_escape: 0.05                                # altezza di sollevamento dell'asta dopo il tiro, per levarsi dal campo
    success_threshold_approach: 0.99                      # soglia di successo moveCartesianPath per l'approccio alla pallina 
    success_threshold_back: 0.20                          # soglia di successo moveCartesianPath per l'arretramento del tiro
