billiard_table:
  pos: [-0.61, -0.33]
  yaw_angle_rad: 0.0
  rialzo_vention: 0.000

balls:
  - color: "white"
    pos: [-0.100, -0.050]  # Posizione rispetto al centro del tavolo
  - color: "red"
    pos: [0.050, 0.050]