billiard_table:
  pos: [-0.3, -0.30]                    # Posizionamento sul banco rispetto al world
  yaw_angle_rad: 0.0                    # Orientamento sul banco rispetto al world  

balls:
  - color: "white"
    pos: [0.0, 0.0]                     # Posizione rispetto al centro del tavolo
  - color: "red"
    pos: [-0.2, -0.05]
  # - color: "blue"
  #   pos: [-0.08, 0.05]
  # - color: "yellow"
  #   pos: [0.15, -0.05]

#per ora usiamo solo palline piene, futura implementazione -> type: "solid" o "striped"