<?xml version="1.0"?>
<package format="3">
  <name>tool_point_calibration</name>
  <version>0.1.0</version>
  <description>
    A simple package that uses the Ceres optimization library to perform simple,
    3-DOF tool-center-point calibration. Users should "touch" the same point in
    space at least three times and record the tool0 position of the robot each
    time. This package then runs an optimization to figure out what the tool
    point is.
  </description>

  <maintainer email="jmeyer@swri.org">Jonathan Meyer</maintainer>
  <author email="jmeyer@swri.org">Jonathan Meyer</author>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>tf2_eigen</depend>
  <depend>geometry_msgs</depend>

  <build_depend>eigen3</build_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
