game_engine:
  ros__parameters:
    use_sim_time: true 
    
    #shot parameters
    velocity_factor: 1.0                              # fattore di moltiplicazione della velocità di tiro (consigliamo non troppo alto, altrimenti il tiro supera i limiti fisici del robot per tiri lontani)


fake_game_engine:
  ros__parameters:
    use_sim_time: true 
    
    # SHOT PARAMETERS (for simulate game engine, used by fake_game_engine)
    direction_angle_deg: -6.74                        # angolo di direzione del tiro rispetto all'asse x del campo in gradi
    impact_shot_velocity: 0.05                         # velocità di impatto asta con pallina del tiro in m/s (0.1 m/s = 10 cm/s)

task_node:
  ros__parameters:

    #----------------------------------------------
    # EXECUTION PARAMETERS

    use_sim_time: true 
    control_execution_by_user_input: false                # se true, il nodo aspetta un input dell'utente per eseguire i comandi di movimento (per debug)
    using_mujoco_simulation: true                         # se true, segnalo al nodo che sto usando MuJoCo come simulatore, quindi il nodo deve aspettare un po' di tempo dopo ogni comando di movimento per far sincronizzare MuJoCo con MoveIt
    #----------------------------------------------



    #----------------------------------------------
    # SHOT PARAMETERS (out of game engine)

    approach_distance_from_ball_surface: 0.01             # distanza di avvicinamento alla pallina in metri (2 cm)
    shooting_distance_from_ball_surface: 0.05             # distanza di tiro dalla pallina in metri (5 cm)
    distance_deceleration_phase_fraction_radius: 2.00     # distanza di decelerazione espressa in frazione del raggio della pallina (1.00 = 1 raggio, 1.5 = 1.5 raggi ecc..) -> Consigliato da 1.5 a 2.0
    impact_angle_deg: 15.0                                # angolo di inclinazione dell'asta rispetto al piano orizzontale in gradi
    offset_correction_center_z: 0.000                     # correzione dell'offset del centro della pallina, per far colpire più in alto rispetto al centro della pallina (in metri)
    elevation_escape: 0.05                                # altezza di sollevamento dell'asta dopo il tiro, per levarsi dal campo
    success_threshold_approach: 0.99                      # soglia di successo moveCartesianPath per l'approccio alla pallina 
    success_threshold_back: 0.20                          # soglia di successo moveCartesianPath per l'arretramento del tiro
    #----------------------------------------------



    #----------------------------------------------
    #PLANNING PARAMETERS

    #generic
    max_velocity_acceleration_scaling_factor: 0.9
    goal_joint_tolerance: 0.001                    # tolleranza di giunto in obiettivi di giunto (radians) -> 1/20 di grado
    goal_position_tolerance: 0.0005                # tolleranza di posizione in obiettivi cartesiani (metri) -> 0.5 mm
    goal_orientation_tolerance: 0.001              # tolleranza di orientamento in obiettivi cartesiani (radians) -> 1/20 di grado

    #moveToJointConfig e moveToNamedTarget:
    def_joint_planning_time: 5.0
    joint_planning_algorithm: "RRTConnectkConfigDefault"
  
    #moveCartesianPath:
    resolution_step: 0.01                         # passo di interpolazione in metri 1cm
   
    #moveCartesianPathAsymmTriangle
    resolution_step_Ruckig: 0.01                        # passo di interpolazione in metri 1cm
    success_threshold_Ruckig: 0.99                      # soglia di successo (percentuale di punti interpolati che devono essere raggiunti)
    Ruckig_dt: 0.01                                     # passo di lavoro di Ruckig in secondi 
    max_jerk: 80.0                                      # jerk massimo in m/s^3 

    #shot method 
    vel_factor_for_jerk_compensation: 1.0               # fattore di moltiplicazione per la velocità per compensare il jerk massimo
    accel_decel_factor_for_jerk_compensation: 1.0       # fattore di moltiplicazione per accelerazione e decelerazione per compensare il jerk massimo 
    #-----------------------------------------------



    #----------------------------------------------
    # SHOT MONITORING, LOGGING AND DEBUG PARAMETERS

    print_EEF_distance_and_position: true  # stampa della distanza e della posizione relativa tra tip dell'asta e pallina bianca alla fine dei movimenti
    log_ruckig_trajectory: true            # log in file della traiettoria calcolata da Ruckig (in moveCartesianPathAsymmTriangle)

    #fase1 -> andare in posa pre-approach
    joints_logging_enabled_1: false
    cartesian_logging_enabled_1: false

    #fase2 -> approach alla pallina
    joints_logging_enabled_2: false
    cartesian_logging_enabled_2: false

    #fase3 -> allontanamento all'indietro per prendere velocità
    joints_logging_enabled_3: false
    cartesian_logging_enabled_3: false

    #fase4 -> tiro
    joints_logging_enabled_4: false
    cartesian_logging_enabled_4: true

    #fase5 -> alzata per liberare il campo
    joints_logging_enabled_5: false
    cartesian_logging_enabled_5: false
    #--------------------------------



    #----------------------------------------------
    # Sezione per MoveIt (nell'URDF di ur_description non ci sono i limiti d'accelerazione che fanno fallire alcuni metodi)
    robot_description_planning:
      joint_limits:
        left_elbow_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_shoulder_lift_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_shoulder_pan_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_wrist_1_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_wrist_2_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_wrist_3_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700


    # SCELTE TRA ALGORITMI DI PLANNING (da ompl_planning.yaml):
    # - APSConfigDefault
    # - SBLkConfigDefault
    # - ESTkConfigDefault
    # - LBKPIECEkConfigDefault
    # - BKPIECEkConfigDefault
    # - KPIECEkConfigDefault
    # - RRTkConfigDefault
    # - RRTConnectkConfigDefault
    # - RRTstarkConfigDefault
    # - TRRTkConfigDefault
    # - PRMkConfigDefault
    # - PRMstarkConfigDefault
    # - FMTkConfigDefault
    # - BFMTkConfigDefault
    # - PDSTkConfigDefault
    # - STRIDEkConfigDefault
    # - BiTRRTkConfigDefault
    # - LBTRRTkConfigDefault
    # - BiESTkConfigDefault
    # - ProjESTkConfigDefault
    # - LazyPRMkConfigDefault
    # - LazyPRMstarkConfigDefault
    # - SPARSkConfigDefault
    # - SPARStwokConfigDefault
    # - TrajOptDefault