fake_game_engine:
  ros__parameters:
    use_sim_time: true 
    
    # SHOT PARAMETERS (for simulate game engine, used by fake_game_engine)
    direction_angle_deg: 35.0                         # angolo di direzione del tiro rispetto all'asse x del campo in gradi
    impact_shot_velocity: 0.10                        # velocità di impatto asta con pallina del tiro in m/s (0.1 m/s = 10 cm/s)


task_node:
  ros__parameters:

    # EXECUTION PARAMETERS
    use_sim_time: true 
    control_execution_by_user_input: false                # se true, il nodo aspetta un input dell'utente per eseguire i comandi di movimento (per debug)


    # SHOT PARAMETERS (out of game engine)
    approach_distance_from_ball_surface: 0.01             # distanza di avvicinamento alla pallina in metri (2 cm)
    shooting_distance_from_ball_surface: 0.05             # distanza di tiro dalla pallina in metri (5 cm)
    impact_angle_deg: 15.0                                # angolo di inclinazione dell'asta rispetto al piano orizzontale in gradi
    offset_correction_center: 0.005                       # correzione dell'offset del centro della pallina, per far colpire la zona 'alta' della pallina
    elevation_escape: 0.05                                # altezza di sollevamento dell'asta dopo il tiro, per levarsi dal campo
    success_threshold_approach: 0.95                      # soglia di successo moveCartesianPath per l'approccio alla pallina 
    success_threshold_shooting: 0.20                      # soglia di successo moveCartesianPath per l'arretramento del tiro
    


    #PLANNING PARAMETERS

    #generic
    max_velocity_acceleration_scaling_factor: 0.3

    #moveToJointConfig e moveToNamedTarget:
    def_joint_planning_time: 5.0
    joint_planning_algorithm: "RRTConnectkConfigDefault"
    goal_joint_tolerance: 0.001                   # ~1/20 di grado (def moveit 0.001 ~1/200 di grado)


    #moveCartesianPath:
    resolution_step: 0.01                         # passo di interpolazione in metri 1cm
   
    #moveCartesianPathAsymmTriangle
    resolution_step_Ruckig: 0.005                        # passo di interpolazione in metri 5mm
    success_threshold_Ruckig: 0.95                       # soglia di successo (percentuale di punti interpolati che devono essere raggiunti)
    Ruckig_dt: 0.01                                      # passo di lavoro di Ruckig in secondi (100Hz)
    max_jerk: 50.0                                       # jerk massimo in m/s^3 (def moveit 10.0)


  
    # Sezione per MoveIt (nell'URDF di ur_description non ci sono i limiti d'accelerazione che fanno fallire alcuni metodi)
    robot_description_planning:
      joint_limits:
        left_elbow_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_shoulder_lift_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_shoulder_pan_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_wrist_1_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_wrist_2_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700
        left_wrist_3_joint:
          has_velocity_limits: true
          max_velocity: 3.14159265
          has_acceleration_limits: true
          max_acceleration: 6.98131700


    # SCELTE TRA ALGORITMI DI PLANNING (da ompl_planning.yaml):
    # - APSConfigDefault
    # - SBLkConfigDefault
    # - ESTkConfigDefault
    # - LBKPIECEkConfigDefault
    # - BKPIECEkConfigDefault
    # - KPIECEkConfigDefault
    # - RRTkConfigDefault
    # - RRTConnectkConfigDefault
    # - RRTstarkConfigDefault
    # - TRRTkConfigDefault
    # - PRMkConfigDefault
    # - PRMstarkConfigDefault
    # - FMTkConfigDefault
    # - BFMTkConfigDefault
    # - PDSTkConfigDefault
    # - STRIDEkConfigDefault
    # - BiTRRTkConfigDefault
    # - LBTRRTkConfigDefault
    # - BiESTkConfigDefault
    # - ProjESTkConfigDefault
    # - LazyPRMkConfigDefault
    # - LazyPRMstarkConfigDefault
    # - SPARSkConfigDefault
    # - SPARStwokConfigDefault
    # - TrajOptDefault